### ISSUE TITLE
/preserv-PE/data/CUS/Cusco/_pk001 make address xlsx

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-PE#1]
/preserv-PE/data/CUS/Cusco/_pk001 
make address

ingest.any_load não suporta ogr2ogr de arquivos xlsx

**Comment by 0e1** [comment]
Para a ingestão de .xlsx usar no layer as opções (dentre as demais necessárias):

```
method: csv2sql
orig_ext: .xlsx
orig_filename: nomeDoArquivoSemExtensao
```

O arquivo .xlsx é convertido para .csv por [`xlsx2csv`](http://manpages.ubuntu.com/manpages/bionic/man1/xlsx2csv.1.html):

`xlsx2csv "$(sandbox)/{{orig_filename}}{{orig_ext}}" {{{method_opts}}} "$(sandbox)/{{orig_filename}}.csv"`

Em `method_opts`é possível indicar a planilha, se houver mais de uma, que se deseja converter, utilizando a opção `-s`.


Lembro que a opção `orig_ext` para o método `csv2sql` se aplica apenas para arquivos `.xlsx`.
